name: Build and Tag Container for PR Code

on: 
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-pr-code:
    uses: ca-risken/.github/.github/workflows/build-pr.yml@main
    with:
      runs_on: codebuild-mimosa-code-pr-runner-${{ github.run_id }}-${{ github.run_attempt }}
      install_go_version: "1.22.12"
      golangci_lint_version: "v1.62.0"
      image_prefix: "risken-code"
      build_opt: "--no-cache --pull"
      test_command: "go-test"
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}